<script src="{{ asset('mdb/js/mdb.min.js') }}"></script>
<script src="{{ asset('fontawesome/js/all.min.js') }}"></script>
<script src="{{ asset('js/mdb.min.js') }}"></script>
<script src="{{asset('js/ui/jquery-3.3.1.min.js')}}"></script>
<script src="{{asset('js/ui/jquery-migrate-3.0.1.min.js')}}"></script>
<script src="{{asset('js/ui/jquery-ui.js')}}"></script>
<script src="{{asset('js/ui/popper.min.js')}}"></script>
<script src="{{asset('js/ui/bootstrap.min.js')}}"></script>
<script src="{{asset('js/ui/owl.carousel.min.js')}}"></script>
<script src="{{asset('js/ui/jquery.stellar.min.js')}}"></script>
<script src="{{asset('js/ui/jquery.countdown.min.js')}}"></script>
<script src="{{asset('js/ui/bootstrap-datepicker.min.js')}}"></script>
<script src="{{asset('js/ui/jquery.easing.1.3.js')}}"></script>
<script src="{{asset('js/ui/aos.js')}}"></script>
<script src="{{asset('js/ui/jquery.fancybox.min.js')}}"></script>
<script src="{{asset('js/ui/jquery.sticky.js')}}"></script>
<script src="{{asset('js/ui/jquery.mb.YTPlayer.min.js')}}"></script>
<script src="{{asset('js/ui/main.js')}}"></script>